-- object and index				
select o.owner , o.object_name , o.subobject_name, rtrim(o.object_type||' '||index_type) object_type  from 
dba_objects o , dba_indexes i
where  o.owner not in ('ANONYMOUS','DBSNMP','SYSADMIN','VEA','VEH','HR','JTI','JTR','JUNK_PS','ODM','ODM_MTR','OE','OLAPSYS',
      'ORDPLUGINS','ORDSYS','OSM','OUTLN','OWAPUB','PERFSTAT','PM','PORTAL30','PORTAL30_DEMO','PORTAL30_PUBLIC','PORTAL30_SSO',
      'PORTAL30_SSO_PS','PORTAL30_SSO_PUBLIC','PTE','PTG','QS','QS_ADM','QS_CB','QS_CBADM','QS_CS','QS_ES','QS_OS','QS_WS',
      'REPADMIN','SCOTT','SH','SSOSDK','SYS','SYSTEM','TRACESVR','WH','WMSYS','XDB','CTSYS','MDSYS','OLAPSVR','OLAPDBA','AURORA$JIS$UTILITY$',
	  'AURORA$ORB$UNAUTHENTICATED','DCM','INTERNET_APPSERVER_REGISTRY','IP','OCA','ORAOCA_PUBLIC','ORASSO','OSE$HTTP$ADMIN','OWA_MGR','UDDISYS',
	  'WFADMIN','WIRELESS','WK_PROXY','WKSYS','WK_Test','CLKRT','ODS','BLEWIS','CDOUGLAS','KWALKER','SPIERSON','DISCOVERER5','DSGATEWAY',
	  'DSSYS','ODSCOMMON','ORASSO_DS','ORASSO_PA','ORASSO_PS','ORASSO_PUBLIC','PORTAL','PORTAL_APP','PORTAL_DEMO','PORTAL_PUBLIC','SYSMAN','AUDSYS')
    and -- option specific schema
    o.owner not in ('CTXSYS','LBACSYS','DVSYS','OJVMSYS','GSMADMIN_INTERNAL','EXFSYS','LBACSYS','MGMT_VIEW','ORDDATA','OWBSYS','SI_INFORMTN_SCHEMA',
				'SYSMAN','WKPROXY','APEX_PUBLIC_USER','DIP','FLOWS_020100','FLOWS_030000','FLOWS_040100','FLOWS_010600','FLOWS_FILES','MDDATA',
				'ORACLE_OCM','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL','SQLTXPLAIN','DMSYS','TSMSYS','APEX_040200','APPQOSSYS',
				'DVF','APEX_030200','TRACESRV','MTMSYS','OWBSYS_AUDIT','WEBSYS')
	and (o.owner,o.object_name) not in 
          (select owner , synonym_name from DBA_SYNONYMS
          where TABLE_owner in  ('ANONYMOUS','DBSNMP','SYSADMIN','VEA','VEH','HR','JTI','JTR','JUNK_PS','ODM','ODM_MTR','OE','OLAPSYS',
                'ORDPLUGINS','ORDSYS','OSM','OUTLN','OWAPUB','PERFSTAT','PM','PORTAL30','PORTAL30_DEMO','PORTAL30_PUBLIC','PORTAL30_SSO',
                'PORTAL30_SSO_PS','PORTAL30_SSO_PUBLIC','PTE','PTG','QS','QS_ADM','QS_CB','QS_CBADM','QS_CS','QS_ES','QS_OS','QS_WS',
                'REPADMIN','SCOTT','SH','SSOSDK','SYS','SYSTEM','TRACESVR','WH','WMSYS','XDB','CTSYS','MDSYS','OLAPSVR','OLAPDBA','AURORA$JIS$UTILITY$',
              'AURORA$ORB$UNAUTHENTICATED','DCM','INTERNET_APPSERVER_REGISTRY','IP','OCA','ORAOCA_PUBLIC','ORASSO','OSE$HTTP$ADMIN','OWA_MGR','UDDISYS',
              'WFADMIN','WIRELESS','WK_PROXY','WKSYS','WK_Test','CLKRT','ODS','BLEWIS','CDOUGLAS','KWALKER','SPIERSON','DISCOVERER5','DSGATEWAY',
              'DSSYS','ODSCOMMON','ORASSO_DS','ORASSO_PA','ORASSO_PS','ORASSO_PUBLIC','PORTAL','PORTAL_APP','PORTAL_DEMO','PORTAL_PUBLIC','SYSMAN','AUDSYS',
              'CTXSYS','LBACSYS','DVSYS','OJVMSYS','GSMADMIN_INTERNAL','EXFSYS','LBACSYS','MGMT_VIEW','ORDDATA','OWBSYS','SI_INFORMTN_SCHEMA',
                  'SYSMAN','WKPROXY','APEX_PUBLIC_USER','DIP','FLOWS_020100','FLOWS_030000','FLOWS_040100','FLOWS_010600','FLOWS_FILES','MDDATA',
                  'ORACLE_OCM','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL','SQLTXPLAIN','DMSYS','TSMSYS','APEX_040200','APPQOSSYS',
                  'DVF','APEX_030200','TRACESRV','MTMSYS','OWBSYS_AUDIT','WEBSYS'))
	and o.object_type not in ('PACKAGE','PACKAGE BODY','FUNCTION','PROCEDURE','TRIGGER','MATERIALIZED VIEW','VIEW')				
	and o.object_type not in ('CLUSTER','CONSUMER GROUP','DESTINATION','DIMENSION','EDITION','EVALUATION CONTEXT',
		'INDEXTYPE','JAVA CLASS','JAVA DATA','JAVA RESOURCE','JAVA SOURCE','JOB CLASS','LIBRARY','OPERATOR','PROGRAM','QUEUE','RESOURCE PLAN',
		'RULE','RULE SET','SCHEDULE','SCHEDULER GROUP','UNDEFINED','UNIFIED AUDIT POLICY','WINDOW','XML SCHEMA')
    and o.owner=i.owner(+)
    and o.object_name=i.index_name(+);		
